ls コマンドを作るオブジェクト指向版
bore-ko/ruby-practices pull request #13
Opened 2024-04-02 12:33 UTC by bore-ko

2024-04-08 15:43 UTC, u1tnk requested changes
大きく言うと以下二点です。指摘しきれない部分もあると思うので全般的に見直してください 💪 

- 機能の分割をしっかりする
- メソッド名/変数名をもっと正確なものにする

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +  def result
ちょっと細かいですが、resultはちょっと抽象的すぎるので 表示するとか出力するとか実行するとかが良いかなーと思いました。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +    @option = {}
optionは複数あるので optionsの方が良いかなと思います。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +  FILE_TYPES = { 'file' => '-', 'directory' => 'd', 'link' => 'l' }.freeze
ちょっと細かいですが

```
FILE_TYPES = { 
  'file' => '-', 
  'directory' => 'd', 
  'link' => 'l', 
}.freeze
```
のように一要素一行にした方が良いですね。追加、削除、並び替えが容易なのと見やすいのが理由です。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +  def initialize(name)
インスタンス変数をたくさん作るのはもったいないので、基本のname、(コストのかかるもの`File.lstat(name)`の結果など)以外はインスタンス変数を作らず、メソッドで取れるようにしましょう。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +    file = File.lstat(name)
ここですが、 `file = File.lstat` のfileの命名はおかしいです。  Fileインスタンスかなと思います。
lstatが返すものをなるべく正確に表すようにましょう。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +    print "total #{@blocks}\n"
メソッド名からして printするのは良くないですね。
また、データを構築する機能とprintする機能をしっかり分けるようにしましょう。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +  def build_current_items_details
item_detailsが FileDetailのインスタンスの配列になっているようですが、 fileとitemの使い分ける意味が無いようなら両方fileにした方が良いですね。
また、currentは必要でしょうか？current以外の item_detailsは無いんじゃないかと思いますし。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +    @items.map { |name| File.lstat(name).blocks }.sum
File.lstatは FileDetail内で実行しており、それは current_item_detailsに入っているはずなのでそれを利用するようにしましょう。
処理が重複しているのと、データを一元化したいというのがあります。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +  def current_items_details_with_spaces
これが返しているのは最大のsizeの文字列長さだと思いますが名前は適当でしょうか？
日本語訳すると「最大のアイテム詳細(複数)を空白と一緒に」となると思います。
nlinkの方も同様です。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +  def print_repeat_current_items_details(file)
print_xxx_複数形で終わっているので配列を表示していそうだと思ったのですが、一件分のようですね。
名前の再検討をお願いします。

また、毎行printを書くのはちょっと非効率だと思うので文字列の連結方法を工夫してprintと分けてみましょう。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/shot_format.rb
> +class ShotFormat
これは Shortの間違いで Shotでしょうか？
提出したあとに一回セルフレビューするなどするとタイプミスも減ると思います。

2024-04-08 15:43 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +    @option.include?(:l) ? LongFormat.new(current_items) : ShotFormat.new(current_items)
クラスはnewで作られて(必要最低限の初期化をして)何らかのメソッドを呼んで中の処理を実行するのが普通なので、newの中でprintまで終わっているのは良くないです。

2024-04-24 12:20 UTC, bore-ko commented on 08.ls_object/ls_command.rb
> +  def result
レビューありがとうございます！
result を 出力するという show に修正しました。

2024-04-24 12:21 UTC, bore-ko commented on 08.ls_object/ls_command.rb
> +    @option = {}
options の複数形にしました！

2024-04-24 12:22 UTC, bore-ko commented on 08.ls_object/file_detail.rb
> +  FILE_TYPES = { 'file' => '-', 'directory' => 'd', 'link' => 'l' }.freeze
> 追加、削除、並び替えが容易なのと見やすいのが理由です。

たしかにそうですね！教えていただきありがとうございます！

2024-04-24 12:24 UTC, bore-ko commented on 08.ls_object/file_detail.rb
> +  def initialize(name)
インスタンス変数は最低限の nameと File.lstat(name) にするようにしました。

2024-04-24 12:27 UTC, bore-ko commented on 08.ls_object/file_detail.rb
> +    file = File.lstat(name)
ファイルの情報を格納したオブジェクトという意味の `@file_stat = File.lstat(name)`に修正しました。

2024-04-24 12:29 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +    print "total #{@blocks}\n"
> データを構築する機能とprintする機能をしっかり分けるようにしましょう。

ここが理解できてませんでした、、build と print を分けるようにします！

2024-04-24 12:33 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +  def build_current_items_details
たしかに file がよさそうですね！

2024-04-24 12:34 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +    @items.map { |name| File.lstat(name).blocks }.sum
FileDetail のインスタンスから利用するようにしました。

2024-04-24 12:38 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +  def current_items_details_with_spaces
名前があきらかにおかしいですね、、すみません直しました🙇‍♂️

2024-04-24 12:43 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +  def print_repeat_current_items_details(file)
一件分ずつのリピートだから複数形ではなく単数形になるんですね！

print は1つにしました。

2024-04-24 12:43 UTC, bore-ko commented on 08.ls_object/shot_format.rb
> +class ShotFormat
失礼しました、修正しました。

2024-04-24 12:45 UTC, bore-ko commented on 08.ls_object/ls_command.rb
> +    @option.include?(:l) ? LongFormat.new(current_items) : ShotFormat.new(current_items)
new の中で print まで終わるのは良くないんですね、処理を分割するようにしました。

2024-04-24 14:43 UTC, u1tnk requested changes
名前付けの改善とクラスの責務をちゃんと分けるところを気をつけてみてください！
責務については綺麗に分けるという事も大事ですが、自分の責務では無いことは知らなくて良いと作りやすくなるというのが大事です。

2024-04-24 14:43 UTC, u1tnk commented on 08.ls_object/file_detail.rb
> +  attr_reader :name, :file_stat
file_statは外部に出す必要は無いですね。
FileDetailクラスを使う側にはfile_statを持っているかどうかは知らないですむよう、FileDetailクラスで適切に使って必要な情報を返すと良いです。

2024-04-24 14:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +    @items.map { |name| FileDetail.new(name).file_stat.blocks }.sum
ここはFileDetailクラスをたた file_statを取得するためだけに使っていてもったいないですね。
https://bootcamp.fjord.jp/pages/utilize-objects

が参考になると思います。

2024-04-24 14:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +    @items.map { |name| File.lstat(name).size.to_s.length }.max
こことその下がFileDetailすら使ってないのは total_blocksと同じことをするのに処理が違うという観点でも良くないですね

2024-04-24 14:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +  def initialize(current_items)
ここの引数は current_itemsとなっていますが、実体はfile名ですよね？
他の部分ではnameを使っているので表記ゆれとなっていそうです。
同じものを指す変数の名前は合わせましょう。

2024-04-24 14:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +  attr_reader :current_items, :items, :block, :max_size, :max_size_for_nlink
ここは全て外部に公開すべき変数ですか？
必要の無いものは隠すようにすると使う方も迷わないですし、このクラスが変更するときも配慮する範囲が減りますので。

2024-04-24 14:43 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +    @block = total_blocks
ここらへんインスタンス変数名とメソッド名があってないのが気になりましたが、そもそもここらへんは current_itemsではなく、file_detailsを持っていれば全て呼ばれたときに計算すれば良いのでインスタンス変数も必要無いですね。

2024-04-24 14:43 UTC, u1tnk commented on 08.ls_object/short_format.rb
> +  def divid_items(added_spaces_filenames)
このdividはスペルミスでしょうか？

2024-04-24 14:43 UTC, u1tnk commented on 08.ls_object/short_format.rb
> +class ShortFormat
LongFormatの方で指摘した内容をこちらでも見てみてください。

2024-04-30 13:05 UTC, bore-ko commented on 08.ls_object/file_detail.rb
> +  attr_reader :name, :file_stat
ありがとうございます！
attr_reader に全部書いてしまってました、file_statを外部に出さないようにしました。

2024-04-30 13:06 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +    @items.map { |name| FileDetail.new(name).file_stat.blocks }.sum
URLもありがとうございます！拝見しました！

2024-04-30 13:07 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +    @items.map { |name| File.lstat(name).size.to_s.length }.max
そうですね、確認するようにします。

2024-04-30 13:08 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +  def initialize(current_items)
こちら  current_items を file_names に修正しました。

2024-04-30 13:11 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +  attr_reader :current_items, :items, :block, :max_size, :max_size_for_nlink
全て外部に公開すべき変数ではありませんでした。ここが理解できてなかったのでご指摘ありがとうございます！
必要ないものは隠すようにしました。

2024-04-30 13:19 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +    @block = total_blocks
ここは悩みました、、file_details のインスタンスを持つように修正しました。
```rb
class LongFormat
  attr_reader :file_details

  def initialize(file_names)
    @file_details = file_names.map { |name| FileDetail.new(name) }
  end
```
LongFormat クラスで  FileDetailを newするだけはおかしいでしょうか？

2024-04-30 13:19 UTC, bore-ko commented on 08.ls_object/short_format.rb
> +  def divid_items(added_spaces_filenames)
失礼しました！！スペルミスです。

2024-04-30 16:13 UTC, u1tnk requested changes
前回見逃してたみたいで申し訳無いですが、クラスの責務のバランスをもう少し見直してください 🙏

2024-04-30 16:13 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +  def create_formats
Formatクラスから formats作ると複数形かな？って思います。
あとクラス名からして名詞の Formatterが良いかと思います。

2024-04-30 16:13 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +  attr_reader :file_details
これ必要？と思って見たんですが、long_formatの責務が少なそうですね。
LsCommandクラスの方は全体の流れだけで良いですね。

2024-04-30 16:13 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +      @formats.build_file_names.each { |file_names| puts file_names.join }
こちらも ここで each/joinなどせずに ShortFormatクラスに任せましょう。
LsCommand側はprintぐらいはやっても良いですが、それ以上はやり過ぎです。

2024-05-10 14:48 UTC, bore-ko commented on 08.ls_object/ls_command.rb
> +  def create_formats
なるほど！ formatsは複数形なのでおかしいんですね、、
create_ formatterに修正しました。

2024-05-10 14:49 UTC, bore-ko commented on 08.ls_object/long_format.rb
> +  attr_reader :file_details
ありがとうございます！
long_formatの責務が少ないため、削除しました。

2024-05-10 14:51 UTC, bore-ko commented on 08.ls_object/ls_command.rb
> +      @formats.build_file_names.each { |file_names| puts file_names.join }
こちらも  ShortFormatクラスに任せるようにしました！

2024-05-11 08:39 UTC, u1tnk requested changes
ちょっと前回混乱させてしまったようですが、
ShortFormatだけあってLongFormatが無いなどバランスの悪い部分の見直しをお願いします 🙏

2024-05-11 08:39 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +    @options.include?(:l) ? file_names : ShortFormat.new(file_names)
create_fromatterという名前で 片方は ShortFormatter、片方は file_namesで文字列の配列と違うものが出てくるのはNGです。
同じクラスである必要は無いですが、同じ動作を期待する互換性のあるクラスのインスタンスを必ず返すようにしましょう。
で、formatterを取得した方は分岐せずに返ってきたformatterを呼ぶだけ！となります。

ちなみに「互換性のある」というちょっと苦しい表現はrubyはduck typpingを使うので継承などが必須では無いので使いました。

2024-05-11 08:39 UTC, u1tnk commented on 08.ls_object/long_format.rb
> +  attr_reader :file_details
これは LsCommandという責務のふんわりしたクラスが責務を持ち過ぎるのでlong_formatの方に移しましょうという意図だったんですが、分かりづらかったようですね 🙏

2024-05-11 08:39 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +  def create_formats
create_formatterにするなら生成するインスタンスのクラス名も Formatterにしないと違和感がありますね。

2024-05-12 09:54 UTC, bore-ko commented on 08.ls_object/ls_command.rb
> +    @options.include?(:l) ? file_names : ShortFormat.new(file_names)
ありがとうございます！
消してしまったのを元に戻してクラスのインスタンスを返すように修正しました。

> formatterを取得した方は分岐せずに返ってきたformatterを呼ぶだけ！となります。

すみません、こちら分からなかったのですが、showメソッドの分岐を削除して formatterを呼ぶようにしました。

2024-05-13 16:59 UTC, u1tnk requested changes

2024-05-13 16:59 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +    formatter
これだと showを呼ぶなら formatterを呼べば良いですね。

と書いていてどうしてこうなっているのかを見たところ initializeの時点で printしている事に気づきました。
前からだと思うので指摘遅れて申しわけないですが、 initializeは最低限の初期化、データの整理などに留めて、他のメソッドで主要な機能を実行するようにしましょう。

2024-05-13 16:59 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +  def file_names
こちらも気づくの遅れましたが、このメソッドのように外部から呼ばれないメソッドは privateにしましょう。

2024-05-20 14:39 UTC, bore-ko commented on 08.ls_object/ls_command.rb
> +    formatter
> 前からだと思うので指摘遅れて申しわけないですが、 initializeは最低限の初期化、データの整理などに留めて、他のメソッドで主要な機能を実行するようにしましょう。

すみません、前からではなく直前の修正で変更したように思います🙇‍♂️ printは最低限の初期化ではないのでメソッドで実行するようにしました。

2024-05-20 14:40 UTC, bore-ko commented on 08.ls_object/ls_command.rb
> +  def file_names
ありがとうございます！
外部から呼ばれないメソッドを privateにしました！

2024-05-22 02:22 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +    @options.include?(:l) ? file_names : ShortFormat.new(file_names)
これは以下のように書けるよって話でした。
疑似コードとして見てください。

```
formatter = long? ? LongFormatter.new : ShortFormatter.new 
formatter.show
```

短いが見づらいかも？なこんな書き方も。
```
(long? ? LongFormatter.new : ShortFormatter.new).show
```

2024-05-22 02:48 UTC, u1tnk requested changes

2024-05-22 02:48 UTC, u1tnk commented on 08.ls_object/ls_command.rb
> +    @options.include?(:l) ? LongFormatter.new(file_names) : ShortFormatter.new(file_names)
lオプションをこことshowで二回評価していますね。formatterだけで大丈夫なはずです。
で、前述した通り、 formatterが表示するコマンドを共通化すればだいぶシンプルになるのでshow/formatter自体一個にできそうですね

2024-05-23 14:42 UTC, bore-ko commented on 08.ls_object/ls_command.rb
> +    @options.include?(:l) ? LongFormatter.new(file_names) : ShortFormatter.new(file_names)
ありがとうございます！
メソッドを共通化することを思い付きませんでした、show/formatterが一個になりとてもシンプルになりました！

2024-05-24 13:09 UTC, u1tnk approved these changes
メソッド名を共通化して違うクラスでも同じように使うのがrubyの duck typeってやつですね 💪

2024-05-24 14:07 UTC, merged