カレンダーのプログラムを作成
bore-ko/ruby-practices pull request #2
Opened 2022-09-24 06:42 UTC by bore-ko

2022-09-29 01:22 UTC, u1tnk requested changes

2022-09-29 01:22 UTC, u1tnk commented on cal.rb
> +  opt.on('-y') {|v| v }
これだと optionがあっても取得したものを保存できていません。

https://docs.ruby-lang.org/ja/latest/class/OptionParser.html

こちらのサンプルのように `opt.on`のブロックの外で定義した変数に保存するようにしましょう。

2022-09-29 01:22 UTC, u1tnk commented on cal.rb
> +  argv = now.year, now.month
rubyは最後の行が返されるので argvに代入する必要は無いです。

また、通常は配列で返すと順番を意識しなければならずちょっとわかりづらいのでhashの方が良いですね。

```
{
  year: now.year,
  month: now.month
}
```

他には引数の年月から Dateインスタンスを作成するのも良い方法ですね。titleメソッドでやっている事をここでやれば良いです。

2022-09-29 01:22 UTC, u1tnk commented on cal.rb
> +  return argv = opt.parse!(ARGV) unless ARGV == []
現状、上述の理由でoptionを取れておらず、引数を順番に返しているだけなので片方だけ指定したり `ruby cal.rb -m 01 -y 2021` とするとエラーになっちゃいます。

2022-09-29 01:22 UTC, u1tnk commented on cal.rb
> +  title
まず、名前が良くないです。 titleというメソッド名だと動詞が無いので、titleをどうするのか分かりません。 titleがreturnされてくるメソッドならありです。

また、このように単純に長いメソッドを分割するだけというのよくある方法ですが、引数や返り値も利用できると良いですね。
それぞれの情報をメソッド内で作った上で返して、 ここでその文字列を全部出力するなどすると分かりやすいですね。

2022-09-29 01:22 UTC, u1tnk commented on cal.rb
> +def calender
他と違い、calendarプログラムのcalendarメソッドなので、メイン処理というのは分かりますが、 `def main`などとした方が一般的だと思います。

2022-09-30 14:29 UTC, bore-ko commented on cal.rb
> +  opt.on('-y') {|v| v }
ARGV.getoptsを使い修正しました。

OptionParserでやろうとしましたが、trueしか取得できませんでした。
```
params = Hash.new
opt = OptionParser.new
opt.on('-y'){|v| params[:y] = v }
opt.on('-m'){|v| params[:m] = v }
opt.parse!(ARGV) 

p params  #=> {:y=>true, :m=>true}
p params[:y]  # => true
```

2022-09-30 14:35 UTC, bore-ko commented on cal.rb
> +  argv = now.year, now.month
titleメソッドを含めたメソッドに変更しました。

> rubyは最後の行が返されるので argvに代入する必要は無いです。

確かに。必要ないですね。戻り値を意識して書くようにします！

2022-09-30 14:39 UTC, bore-ko commented on cal.rb
> +  return argv = opt.parse!(ARGV) unless ARGV == []
修正後、エラーにならないことを確認しました。

2022-09-30 14:46 UTC, bore-ko commented on cal.rb
> +  title
引数や返り値を利用、そして文字列を全部出力するようにしました。

2022-09-30 14:48 UTC, bore-ko commented on cal.rb
> +def calender
一般的な `def main`に変更しました。

2022-10-02 14:25 UTC, u1tnk commented on cal.rb
> +  opt.on('-y') {|v| v }
`opt.on('-y VALUE') `みたいに引数を取る事を指定すると、取れます。

getoptsで取れれば大丈夫です 🙆‍♀️

2022-10-02 14:27 UTC, u1tnk requested changes
諸々変更確認しました。
指摘したインスタンス変数の部分対応してもらえれば良さそうです。

2022-10-02 14:27 UTC, u1tnk commented on cal.rb
> +    @year = today.year
クラスを使わないときに `@hoge`とインスタンス変数を使うのはNGです。
データの流れが分かりづらいのが理由です。

引数と返り値で受け渡すようにしましょう。

2022-10-08 09:14 UTC, bore-ko commented on cal.rb
> +  opt.on('-y') {|v| v }
教えてくださりありがとうございます 🙇‍♂️ `opt.on()`に引数をとる事を指定すると`params[:y]`で値が取れました！

2022-10-08 09:22 UTC, bore-ko commented on cal.rb
> +    @year = today.year
知りませんでした...。教えてくださりありがとうございます！
考えてみると、クラスを使わないときのインスタンス変数は、なんのインスタンスなんだろうとも思いました。修正します。

2022-10-08 09:37 UTC, bore-ko commented
- インスタンス変数をローカル変数に変更しました。
別の場所も修正しました。何度も変えてすみません。お手数をおかけします。

- 色の反転に挑戦しましたが、できませんでした。
わかったのはここまででした。
```rb
today = 8
puts "\e[30m\e[47m\"#{today}\"\e[0m"
```
<img width="140" alt="image" src="https://user-images.githubusercontent.com/110995507/194700830-316dd246-a884-4620-a967-542893785fea.png">

2022-10-09 00:09 UTC, u1tnk requested changes
引数指定して返り値を利用することはできていますね 👍 

各箇所コメントしていますが、次は「変数/メソッド名と内容を一致させる」事を徹底してください。

また、メソッド名のつけかたですが、

`動詞_名詞` で、「何かに対して何かをする」という形式が基本です。
ruby文化では、その中で単純に何かを返すメソッドであれば `名詞` だけにします。 first_dayなどはそうなっていますね。

2022-10-09 00:09 UTC, u1tnk commented on cal.rb
> +  now = Date.today
nowだと日付内の概念が含まれますが、todayだと日付までの範囲となるので変数名が不適切だと思います。直下にtoday変数があるのでなおさらです。
また、todayで year/month情報を含むhashを作っていますが、 Date型のインスタンスでyear/monthを持てるのでhashを作る必要はありません。

2022-10-09 00:09 UTC, u1tnk commented on cal.rb
> +def return_the_date
returnとtheに特に重要な情報が無いので削りましょう。dateも何の日か分かりませんのでこの状態だと日付型の何かを返すとしか分かりません。
他のメソッドが first_day/last_dayなので合わせて欲しいです。

2022-10-09 00:09 UTC, u1tnk commented on cal.rb
> +def week(date)
変数名からすると「一週間分の何か」が返って来そうですが、一日分を出力するだけとなっていますので名前を変更しましょう。

2022-10-09 00:09 UTC, u1tnk commented on cal.rb
> +    puts one_week
この部分、if/elseで差は `改行を出力する` だけのはずなので、他の部分の出力は分岐せず、改行の出力のみを判断すれば良いと思います。

2022-10-09 00:09 UTC, u1tnk commented on cal.rb
> +    puts one_week
メソッド内は情報の取得、mainで出力という方針が基本のようなので、メソッド内で出力するのは違和感があります。
作るとしても出力するメソッドだと分かるように `print_xxx`/`output_xxx` などの名前にした方が良いですね。

2022-10-10 03:41 UTC, bore-ko commented on cal.rb
> +  now = Date.today
nowとtodayの違いをあまり意識していませんでした。
また、Date型のインスタンスがあるので、hashを作る必要がないことを確認しました。

2022-10-10 03:46 UTC, bore-ko commented on cal.rb
> +def return_the_date
メソッド名 return_the_dateを、todayに変更しました。他のメソッドの first_day/last_dayに合わせて〇〇dayという名詞ということを考えて選びました。

2022-10-10 03:55 UTC, bore-ko commented on cal.rb
> +def week(date)
変数名と中身が違うことを確認しました。下記のご指摘により、mainへweekの処理を移動しました。mainで全部を出力すると始めから言われておりましたが、メソッドに分けるのが面白くて変えてしまいました。すみません。

2022-10-10 04:01 UTC, bore-ko commented on cal.rb
> +    puts one_week
ifを変更しました。改行を出力することのみを考えてみました。ご確認お願いいたします。

2022-10-10 14:42 UTC, u1tnk requested changes

2022-10-10 14:42 UTC, u1tnk commented on cal.rb
> +main(today)
main関数は何も渡さずに呼ぶのが普通なので todayは中で呼ぶようにしましょう。

2022-10-10 14:42 UTC, u1tnk commented on cal.rb
> +      day.gsub!("\"", '')
上の文字列に余計なダブルクォートがあるので削除すればこの行は不要です。

2022-10-10 14:42 UTC, u1tnk commented on cal.rb
> +      day.delete!(' ')
細かいのですが、余計なときだけ消すというのはあまりよく無いですね。
できれば不要なときは空白を足さないようにすると良いと思います。

日付→空白or改行の順番になるはずなので、日付出力するときに日付だけ反転するようにするようにできます。

一桁の反転は空白も込みになっちゃってますね。
strftimeでは無く、日付だけを文字列化して…とやれば文字だけ反転もできますが、歓迎要件なので、空白も込みで反転していても大丈夫です。

2022-10-11 13:14 UTC, bore-ko commented on cal.rb
> +main(today)
修正しました。変数名で悩みました。todayを中で呼んで使うために、変数`date`に`today`を代入しました。一番はじめの`today`メソッドも`date`を返り値としていますが、変数名はおかしくはないでしょうか。
また、main内のブロック変数名を`d`にしましたが、大丈夫でしょうか。良い名前が分かりませんでした。

2022-10-11 13:18 UTC, bore-ko commented on cal.rb
> +      day.gsub!("\"", '')
シーケンスの余計なダブルクォートを見つけ削除しました。

2022-10-11 13:34 UTC, bore-ko commented on cal.rb
> +      day.delete!(' ')
細かいところも教えていただき、学びになりました！
色の反転も修正しました。日付だけを文字列化して、日付の文字色を反転して、空白、改行をくわえました。
コードが長くなってしまいましたが、ご確認いただけますと幸いです。

2022-10-12 02:26 UTC, u1tnk requested changes

2022-10-12 02:26 UTC, u1tnk commented on cal.rb
> +  date = today
こういうパターンは悩みますね。

メソッドと変数が同じになるときは `today = calc_today`など、省略した動詞を付けるのはアリかなと思います。

ただ、今回の場合だとこの変数はtodayでは無いと思います。日付型ですが、月の部分までしか使わないので xxx_monthとかでも良いと思います。

2022-10-12 02:26 UTC, u1tnk commented on cal.rb
> +  (first_day(date)..last_day(date)).each do |d|
これは dと dayの区別が難しいですね。
ブロックの長さ的には一文字でも良いのですが、 day変数の名前からdayの方が日付型のデータと勘違いしそうです。
目的からすると `buffer`/`output_string`/`day_string`…とかになるでしょうか。

あとは処理が現状ちゃんと出力順にならんでいるので、順番に出力していてday変数を作らないのも一つの方法ですね。

2022-10-13 03:30 UTC, bore-ko commented on cal.rb
> +  (first_day(date)..last_day(date)).each do |d|
ありがとうございます。
dayを`day_string`に変更、dをもとの`day`に戻しました。

day変数を作らない方法は苦戦しました。

2022-10-13 03:38 UTC, bore-ko commented on cal.rb
> +  date = today
私の認識が合ってますでしょうか？
```
def main
  year_month = today
```
と変更しました。
today 自体を変更した方がよかったでしょうか...。

2022-10-13 05:05 UTC, u1tnk requested changes

2022-10-13 05:05 UTC, u1tnk commented on cal.rb
> +  year_month = today
year_monthという変数名は良いのですが、

`year_month = today`

というのがおかしいのでメソッド名の修正お願いします 🙏

2022-10-13 05:05 UTC, u1tnk commented on cal.rb
> +    day_string.prepend(' ') if day_string == '1' || day_string == '2' || day_string == '3' || day_string == '4' || day_string == '5' || day_string == '6' || day_string == '7' || day_string == '8' ||
ここは `||` で繋げるのは冗長ですね。 数値にして範囲でチェックするとか range( 1..9 みたいなやつです)を使うと短く、見やすくなります。

また、Stringクラスの便利なメソッドを使うとif文を使わなくても良くなります。

2022-10-14 03:37 UTC, bore-ko commented on cal.rb
> +  year_month = today
`year_month = today`を`month = calc_month`に修正しました。

カレンダーはひと月を表示するプログラム。よって今日`today`ではないと思いました。

変数名は、`month`と`year_month`でどちらにしようかと思い、
`year_month`は丁寧で分かりやすい。今回の calc_month の流れからは`month`がシンプルでいいかなと考えました。

2022-10-14 03:45 UTC, bore-ko commented on cal.rb
> +    day_string.prepend(' ') if day_string == '1' || day_string == '2' || day_string == '3' || day_string == '4' || day_string == '5' || day_string == '6' || day_string == '7' || day_string == '8' ||
`sub`メソッドを使いif文を変更しました。

`sub!`と迷いました。(day_string に代入する必要がないため)
使いわけがよく分かりませんが、破壊的な変更はなるべく使わない方がいいというイメージで sbuと考えました。

2022-10-14 15:19 UTC, u1tnk requested changes

2022-10-14 15:19 UTC, u1tnk commented on cal.rb
> +    day_string = day_string.sub(/\A[1-9]\z/, ' ' + day_string)
惜しい！

すぐ教えるのはよくないと思ったのですが、ドキュメント調べるのはできているので正解を書くので使ってみてくだだい。

こちらです https://docs.ruby-lang.org/ja/latest/method/String/i/rjust.html

2022-10-15 05:10 UTC, bore-ko commented on cal.rb
> +    day_string = day_string.sub(/\A[1-9]\z/, ' ' + day_string)
ありがとうございます！

使ってみました。右詰めと空白を1行にしましたが、書き方大丈夫でしょうか。

2022-10-16 02:08 UTC, u1tnk approved these changes

2022-10-16 05:01 UTC, merged